spring:
  application:
    name: hms
  datasource:
    url: jdbc:${DB_URL:mysql://localhost:3306/hms_db?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:8080}
admin:
  email: ${ADMIN_EMAIL:admin@hms.com}
  password: ${ADMIN_PASSWORD:admin123}
jwt:
  secret: ${JWT_SECRET:gajsdhjagsdgadsgjtbqwytebqwtyqbtsddyuagsdgasdjhasdjgajsdgagsdjgasjdgjhasgdhgasdgqwenbsdoiqweoiquweqweqwe}
  expirytime: ${JWT_EXPIRY:86400000}