spring:
  application:
    name: hms
  datasource:
    url: jdbc:${DB_URL:mysql://localhost:3306/hms_db?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
server:
  port: ${PORT:8080}